### ISSUE TITLE
Windows GUI layout problems on ultrawide monitor

### ISSUE THREAD

**Issue by MikeSullivan7** [mantidproject/mantidimaging#1968]
### Summary

When using Mantid Imaging on Windows on an ultrawide monitor (2560 x 1080), the GUI layout does not display correctly.

### Steps To Reproduce

Check how Qt widget sizing dynamically changes depending on monitor resolution and make the layout resolution-independent.

### Expected Behaviour

GUI should be consistent across different monitor resolutions

### Current Behaviour

Some parts of the GUI are not in the correct position or size when displayed on an ultrawide monitor e.g. sliders, scale, buttons.

### Context

main branch

### Screenshot(s)

Standard monitor:
![image](https://github.com/mantidproject/mantidimaging/assets/30868085/53a06377-6600-433c-a913-deedc8254edf)

Ultrawide monitor:
![image](https://github.com/mantidproject/mantidimaging/assets/30868085/9f6096ac-373d-4400-beae-8b090d4c4274)

**Comment by samtygier-stfc** [comment]
Symptoms look a lot like https://github.com/pyqtgraph/pyqtgraph/issues/1250 , but that should have been fixed in pyqtgraph. Can you check which version you have installed `mamba list pyqtgraph`. Otherwise that issue is probably a good place to start researching.

**Comment by MikeSullivan7** [comment]
I'm running pyqtgraph 0.13.3 which is the latest version but still having issues. This will take more investigation...

**Comment by JackEAllen** [comment]
May be worth renaming this to Windows GUI resolution layout problems as MI looks fine on windows on my ultra-wide with scaled down resolution.
